export const CHANGE_MATRICULE = 'CHANGE_MATRICULE';
export const CHANGE_NOMEQUIPEMENT = 'CHANGE_NOMEQUIPEMENT';
export const CHANGE_QUANTITE = 'CHANGE_QUANTITE';
export const CHANGE_TYPE_DE_DEMANDE = 'CHANGE_TYPE_DE_DEMANDE';
export const ADD_DATA = 'ADD_DATA';
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS';
export const ADD_DATA_ERROR = 'ADD_DATA_ERROR';